[build]
  # Dossier principal où se trouve le code React
  base = "frontend/gymrat-marketplace"
  
  # Commande de build (CI=false empêche les warnings ESLint de faire planter le build)
  command = "CI=false npm run build"
  
  # Le dossier généré par React contenant le site web final (chemin relatif au "base")
  publish = "build"

# Redirection essentielle pour React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
